# Introduction to OOP(object oriented programming) in Python
  one of the popular approach to solve a programming problem by creating an objects . This is known as object oriented programming.
  
  An object has two characteristics :
    1. attributes(name,age,color)
    2.behaviour (dance)

In [3]:
def test():
    print('test() for function')
    return
test()

test() for function


In [4]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
    
obj=Demo()
obj.test()


test() for the class and method


In [19]:
class Demo1:
    def fact(self,n):
        #return factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=Demo1()
p1.fact(5)

120

In [20]:
class Demo2:
    def accept(self,p1,p2):
        a=p1
        b=p2
        return
    def display(self):
        print("a= ",a)
        print("b= ",b)
        
c1=Demo2()
c1.accept(10,20)
c1.display()

NameError: name 'a' is not defined

In [35]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=Demo2(10,20)
print(c1.add(100,200))
    

300


In [38]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def multi(self,p1,p2):
        return p1*p2
c1=Demo2(10,20)
print(c1.multi(100,200))
    

20000


In [40]:
import re
sentence='we are humans'
matched=re.match(r'(.*) (.*?) (.*)',sentence)
print(matched.group(2))

are


In [41]:
#some inheritance
# parent class
class person(object):
    #constructer
    def __init__(self,name):
        self.name=name
    def __init__()

SyntaxError: invalid syntax (<ipython-input-41-4f1899d8fb4a>, line 7)

# Python Numpy
  NumPy is a bit like python list
  
  NumPy array is a central data structure of 
  

In [46]:
list=[1,2,3,4]
print(list)

[1, 2, 3, 4]


In [44]:
import numpy as np
list=[1,2,3,4]
array=np.array(list)
print(array)

[1 2 3 4]


In [45]:
list=[1,2,3,4]
array=np.array(list)
print(array.shape)
print(array.dtype)

(4,)
int32


In [48]:
list=[1.0,2.2,3.4,5.0]
array=np.array(list)
print(array.shape)
print(array.dtype)

(4,)
float64


In [51]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [53]:
# reshape the given array
# numpy.reshape(arrayName,reshape,order='C')
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [56]:
#append some data-- horizontally
#append some data-- vertical
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [58]:
#append some data -- vertical
#vstack(array1,array2)-- will be automatically arranged
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [60]:
#generate random number from NP
a1=np.random.normal(5,0.5,10)
print(a1)

[5.03958076 4.99730106 4.98545045 5.93027574 5.95722792 5.37301647
 4.53419031 4.71486562 4.70945528 3.93834441]


In [69]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [71]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [74]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [79]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=8
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1  8]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [82]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [91]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [93]:
# indexing and slicing of numpy
a1=np.array([(1,2,3),(4,5,6)])
print("first row :",a1[0])

first row : [1 2 3]


In [96]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row :",a1[1])

second row : [4 5 6]


In [101]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing last column :",a1[:,2])

slicing last column : [3 6]


In [102]:
a1=np.array([(1,2,3),(4,5,6)])
print("row and column :",a1[1,:1])

row and column : [4]


In [105]:
a1=np.random.normal(5,1,10)
print(a1)
print("min value= ",np.min(a1))
print("max value= ",np.max(a1))
print("mean value= ",np.mean(a1))
print("median value= ",np.median(a1))

[3.96291786 5.28952345 3.01001449 4.66002872 3.76049158 3.38830927
 5.05534041 4.05685307 5.21492306 2.72935489]
min value=  2.729354894370742
max value=  5.289523448403698
mean value=  4.1127756802755355
median value=  4.009885466679831


In [107]:
# multiple of 1D arrays
# numpy.dot(x,y) --

c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)





14

In [109]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [110]:
b1=np.array([(1,5),[]])

In [ ]:
class Foo:
    def printline()